### ISSUE TITLE
Documenting UI Templates

### ISSUE THREAD

**Issue by Ririio** [Seneca-CDOT/starchart#37] opened 2023-01-26 00:36 UTC
To ensure that those who contribute on the creation of the UI of the website, must follow a template to prevent conflicting design.

- Contributors must document and compile all UI templates
- Template must be easy to read, and understand by non-front-end contributors
  - Is not final, and can be customized by all contributors

**Comment by Ririio** [comment] 2023-01-26 02:40
We'll be using figma, and anyone who wants to participate can edit through this [linl](https://www.figma.com/file/88QbX1uesxfysuRPQNMv0l/Chakra-UI-Figma-Kit-(Community)?node-id=2102%3A2109&t=g5dTwpmysSz5GNPo-1)

**Comment by dadolhay** [comment] 2023-01-30 16:16
Duplicate of #58

**Closed by dadolhay** 2023-01-30 16:16 UTC
Labels: documentation
